# Generated by Django 5.2.5 on 2025-08-31 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_useranswer_is_correct_useranswer_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
    ]
