# Generated by Django 5.2.5 on 2025-09-04 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_remove_useranswer_is_correct_alter_question_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='is_correst_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='test',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', related_query_name='user_answer', to='models.test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', related_query_name='user_answer', to='models.answer', verbose_name='Вариант ответа'),
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
