# Generated by Django 5.2.5 on 2025-09-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_useranswer_is_correst_answer_useranswer_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', related_query_name='user_answer', to='models.test', verbose_name='Тест'),
        ),
    ]
