# Generated by Django 5.2.5 on 2025-09-07 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_answer_user_question_user_test_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', related_query_name='answer', to='models.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions', related_query_name='question', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='test',
            name='user',
            field=models.ManyToManyField(related_name='tests', related_query_name='test', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
