# Generated by Django 5.2.5 on 2025-09-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_alter_answer_question_alter_question_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.IntegerField(choices=[(0, 'Нет'), (1, 'Да')], default=0),
        ),
    ]
