# Generated by Django 5.2.5 on 2025-09-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_alter_answer_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='is_correst_answer',
            field=models.IntegerField(choices=[(0, 'Нет'), (1, 'Да')], default=0),
        ),
    ]
