# Generated by Django 5.2.5 on 2025-09-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_alter_useranswer_is_correst_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='is_correst_answer',
            new_name='is_correct_answer',
        ),
    ]
